### ISSUE TITLE
Cannot associate with camel-cased class name

### ISSUE THREAD

**Issue by graft** [jackdempsey/sequel_polymorphic#11]
The latest commit (e35f52844295c315ade7f40620697da474b6e24c) breaks my associations (although it fixed my issue with 'constantize', which is good); I have a column type that is camel-cased (i.e., clinical_type: "ClinicalColorectal"). Calling capitalize on this value results in incorrect behavior, and the association fails because it cannot find a class named "Clinicalcolorectal". I'm not sure why it should be necessary to transform able_type when loading - surely this column should be written with the exact class name?

**Comment by kuraga** [comment]
Our fault. There had been `capitalize` in another place when came a maintainer. Should be `underscore` in that place and other.

Possible fixed in https://github.com/jackdempsey/sequel_polymorphic/commit/9c400a10afcf6468694e5439822dd8cd9934b72b.

@graft @Draiken @nazipov can you check if your code work **using `master`** branch, please?

**Comment by nazipov** [comment]
@kuraga Yes, it works!

**Comment by graft** [comment]
@kuraga works for me, thanks for the quick update!

**Comment by kuraga** [comment]
Released `v0.2.2'
